// <auto-generated />
namespace Recruiting.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class EliminadocampoNombredeCandidatura : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EliminadocampoNombredeCandidatura));
        
        string IMigrationMetadata.Id
        {
            get { return "201505061529523_Eliminado campo Nombre de Candidatura"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
