// <auto-generated />
namespace Recruiting.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class AddEstadoOrigenRelacionVistaEtapa : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddEstadoOrigenRelacionVistaEtapa));
        
        string IMigrationMetadata.Id
        {
            get { return "201504301125488_Add Estado Origen RelacionVistaEtapa"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
