// <auto-generated />
namespace Recruiting.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class AddCentro_toCorreoPlantilla : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddCentro_toCorreoPlantilla));
        
        string IMigrationMetadata.Id
        {
            get { return "201604010656264_AddCentro_toCorreoPlantilla"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
