// <auto-generated />
namespace Recruiting.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Motivoderenuncia : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Motivoderenuncia));
        
        string IMigrationMetadata.Id
        {
            get { return "201606211405005_Motivo de renuncia"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
