// <auto-generated />
namespace Recruiting.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class aniadir_avisarAlCAndidato_a_entrevistas : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(aniadir_avisarAlCAndidato_a_entrevistas));
        
        string IMigrationMetadata.Id
        {
            get { return "201706301133404_aniadir_avisarAlCAndidato_a_entrevistas"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
