// <auto-generated />
namespace Recruiting.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class aniadido_campo_GrupoNecesidadId_a_Necesidad : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(aniadido_campo_GrupoNecesidadId_a_Necesidad));
        
        string IMigrationMetadata.Id
        {
            get { return "201708311120084_aniadido_campo_GrupoNecesidadId_a_Necesidad"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
