// <auto-generated />
namespace Recruiting.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Eliminar_campo_SalarioDeseado_de_tabla_dbo_candidato : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Eliminar_campo_SalarioDeseado_de_tabla_dbo_candidato));
        
        string IMigrationMetadata.Id
        {
            get { return "201705041445434_Eliminar_campo_SalarioDeseado_de_tabla_dbo_candidato"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
