// <auto-generated />
namespace Recruiting.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class aniadir_campo_moneda_a_candidatura : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(aniadir_campo_moneda_a_candidatura));
        
        string IMigrationMetadata.Id
        {
            get { return "201706021123340_aniadir_campo_moneda_a_candidatura"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
