// <auto-generated />
namespace Recruiting.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class aniadida_tabla_Oficina : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(aniadida_tabla_Oficina));
        
        string IMigrationMetadata.Id
        {
            get { return "201708180941278_aniadida_tabla_Oficina"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
