// <auto-generated />
namespace Recruiting.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class eliminar_entrevista_completada : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(eliminar_entrevista_completada));
        
        string IMigrationMetadata.Id
        {
            get { return "201709151022309_eliminar_entrevista_completada"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
