// <auto-generated />
namespace Recruiting.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Nueva_Tabla_FenixCategoriaLineaCelda : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Nueva_Tabla_FenixCategoriaLineaCelda));
        
        string IMigrationMetadata.Id
        {
            get { return "201705310910438_Nueva_Tabla_FenixCategoriaLineaCelda"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
