// <auto-generated />
namespace Recruiting.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class aniadido_ModuloId_para_crear_FK_con_Maestro : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(aniadido_ModuloId_para_crear_FK_con_Maestro));
        
        string IMigrationMetadata.Id
        {
            get { return "201706211029200_aniadido_ModuloId_para_crear_FK_con_Maestro"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
