// <auto-generated />
namespace Recruiting.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class added_modifiableEntity_data_to_GrupoNecesidad : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_modifiableEntity_data_to_GrupoNecesidad));
        
        string IMigrationMetadata.Id
        {
            get { return "201709051028392_added_modifiableEntity_data_to_GrupoNecesidad"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
