// <auto-generated />
namespace Recruiting.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class RTOOLS10_Anhadir_origenCV_FuenteReclutamiento : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RTOOLS10_Anhadir_origenCV_FuenteReclutamiento));
        
        string IMigrationMetadata.Id
        {
            get { return "201710251049343_RTOOLS-10_Anhadir_origenCV_FuenteReclutamiento"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
