// <auto-generated />
namespace Recruiting.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class aniadir_tabla_subEntrevista : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(aniadir_tabla_subEntrevista));
        
        string IMigrationMetadata.Id
        {
            get { return "201706060904156_aniadir_tabla_subEntrevista"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
