// <auto-generated />
namespace Recruiting.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Modificado_tabla_PersonasLibres_FechaLiberacion_y_Tecnologia : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Modificado_tabla_PersonasLibres_FechaLiberacion_y_Tecnologia));
        
        string IMigrationMetadata.Id
        {
            get { return "201705231011242_Modificado_tabla_PersonasLibres_FechaLiberacion_y_Tecnologia"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
