// <auto-generated />
namespace Recruiting.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class eliminar_campos_ComentariosRenuncia_y_motivoRenunciaId_de_Candidatura : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(eliminar_campos_ComentariosRenuncia_y_motivoRenunciaId_de_Candidatura));
        
        string IMigrationMetadata.Id
        {
            get { return "201710171031085_eliminar_campos_ComentariosRenuncia_y_motivoRenunciaId_de_Candidatura"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
