// <auto-generated />
namespace Recruiting.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Aniadir_PersonaAsignada_a_BitacoraNecesidad : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Aniadir_PersonaAsignada_a_BitacoraNecesidad));
        
        string IMigrationMetadata.Id
        {
            get { return "201711241005583_Aniadir_PersonaAsignada_a_BitacoraNecesidad"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
