// <auto-generated />
namespace Recruiting.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class added_SubEntrevistaId_to_Correos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_SubEntrevistaId_to_Correos));
        
        string IMigrationMetadata.Id
        {
            get { return "201706141511114_added_SubEntrevistaId_to_Correos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
