// <auto-generated />
namespace Recruiting.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class aniadir_campos_ComentariosRenunciaDescarte_y_motivoRenunciaDescarteId_a_Candidatura : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(aniadir_campos_ComentariosRenunciaDescarte_y_motivoRenunciaDescarteId_a_Candidatura));
        
        string IMigrationMetadata.Id
        {
            get { return "201710171010320_aniadir_campos_ComentariosRenunciaDescarte_y_motivoRenunciaDescarteId_a_Candidatura"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
