// <auto-generated />
namespace Recruiting.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Incluir_Persona_Cuenta_Proyecto_en_Necesidad : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Incluir_Persona_Cuenta_Proyecto_en_Necesidad));
        
        string IMigrationMetadata.Id
        {
            get { return "201710301042163_Incluir_Persona_Cuenta_Proyecto_en_Necesidad"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
