// <auto-generated />
namespace Recruiting.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Agregado_Campo_CandidaturaOfertaId_A_Candidaturas : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Agregado_Campo_CandidaturaOfertaId_A_Candidaturas));
        
        string IMigrationMetadata.Id
        {
            get { return "201806110719260_Agregado_Campo_CandidaturaOfertaId_A_Candidaturas"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
