// <auto-generated />
namespace Recruiting.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Corregir_Nombre_Columna_BecarioId_de_TablaBitacoraBecario : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Corregir_Nombre_Columna_BecarioId_de_TablaBitacoraBecario));
        
        string IMigrationMetadata.Id
        {
            get { return "201802011618122_Corregir_Nombre_Columna_BecarioId_de_TablaBitacoraBecario"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
