// <auto-generated />
namespace Recruiting.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Aniadir_PersonaConvocatoriaId_y_ResponsableId_A_BecarioObservacion : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Aniadir_PersonaConvocatoriaId_y_ResponsableId_A_BecarioObservacion));
        
        string IMigrationMetadata.Id
        {
            get { return "201801291244574_Aniadir_PersonaConvocatoriaId_y_ResponsableId_A_BecarioObservacion"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
