// <auto-generated />
namespace Recruiting.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Eliminar_Responsable_BecariosObservaciones : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Eliminar_Responsable_BecariosObservaciones));
        
        string IMigrationMetadata.Id
        {
            get { return "201802151114205_Eliminar_Responsable_BecariosObservaciones"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
