// <auto-generated />
namespace Recruiting.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Creada_Tabla_CandidaturaOferta : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Creada_Tabla_CandidaturaOferta));
        
        string IMigrationMetadata.Id
        {
            get { return "201806081017446_Creada_Tabla_CandidaturaOferta"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
