// <auto-generated />
namespace Recruiting.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Modificar_Longitud_Campo_Comentario_PersonaLibre : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Modificar_Longitud_Campo_Comentario_PersonaLibre));
        
        string IMigrationMetadata.Id
        {
            get { return "201807100718577_Modificar_Longitud_Campo_Comentario_PersonaLibre"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
