// <auto-generated />
namespace Recruiting.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Aniadidos_ObservacionProceso_Y_SuperaProceso_a_Becario : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Aniadidos_ObservacionProceso_Y_SuperaProceso_a_Becario));
        
        string IMigrationMetadata.Id
        {
            get { return "201801261018160_Aniadidos_ObservacionProceso_Y_SuperaProceso_a_Becario"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
