// <auto-generated />
namespace Recruiting.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Aniadir_Tabla_BitacoraBecario : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Aniadir_Tabla_BitacoraBecario));
        
        string IMigrationMetadata.Id
        {
            get { return "201801301142382_Aniadir_Tabla_BitacoraBecario"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
