// <auto-generated />
namespace Recruiting.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Cambio_Tabla_Aniosexp : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Cambio_Tabla_Aniosexp));
        
        string IMigrationMetadata.Id
        {
            get { return "201903080740221_Cambio_Tabla_Aniosexp"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
