// <auto-generated />
namespace Recruiting.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class delete_aniosexperienciacandidato : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(delete_aniosexperienciacandidato));
        
        string IMigrationMetadata.Id
        {
            get { return "201903080951140_delete_aniosexperienciacandidato"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
