//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Invalida la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a API usada para la convocatoria de salas de recruiting.
        /// </summary>
        internal static string About_Description {
            get {
                return ResourceManager.GetString("About_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar Token.
        /// </summary>
        internal static string ActualizarToken {
            get {
                return ResourceManager.GetString("ActualizarToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a API Graph Recruiting.
        /// </summary>
        internal static string App_Name {
            get {
                return ResourceManager.GetString("App_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Prototipo Fase II.
        /// </summary>
        internal static string App_Name_Short {
            get {
                return ResourceManager.GetString("App_Name_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Caller needs to authenticate..
        /// </summary>
        internal static string Error_AuthChallengeNeeded {
            get {
                return ResourceManager.GetString("Error_AuthChallengeNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error occurred while processing your request..
        /// </summary>
        internal static string Error_Introduction {
            get {
                return ResourceManager.GetString("Error_Introduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error in .
        /// </summary>
        internal static string Error_Message {
            get {
                return ResourceManager.GetString("Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Find Meeting Times .
        /// </summary>
        internal static string Graph_FindMeetingTimes_Button {
            get {
                return ResourceManager.GetString("Graph_FindMeetingTimes_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Find Meeting Times.
        /// </summary>
        internal static string Graph_FindMeetingTimes_Heading {
            get {
                return ResourceManager.GetString("Graph_FindMeetingTimes_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Click here to get all the meeting times availables..
        /// </summary>
        internal static string Graph_FindMeetingTimes_Instruction {
            get {
                return ResourceManager.GetString("Graph_FindMeetingTimes_Instruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Meeting Times Availables.
        /// </summary>
        internal static string Graph_FindMeetingTimes_Results_Label {
            get {
                return ResourceManager.GetString("Graph_FindMeetingTimes_Results_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Get email address.
        /// </summary>
        internal static string Graph_GetEmailAddress_Button {
            get {
                return ResourceManager.GetString("Graph_GetEmailAddress_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Get email address.
        /// </summary>
        internal static string Graph_GetEmailAddress_Heading {
            get {
                return ResourceManager.GetString("Graph_GetEmailAddress_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Choose the &lt;b&gt;Get email address&lt;/b&gt; button to get the current user&apos;s email address:.
        /// </summary>
        internal static string Graph_GetEmailAddress_Instruction {
            get {
                return ResourceManager.GetString("Graph_GetEmailAddress_Instruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Current user&apos;s email address.
        /// </summary>
        internal static string Graph_GetEmailAddress_Results_Label {
            get {
                return ResourceManager.GetString("Graph_GetEmailAddress_Results_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Get Rooms.
        /// </summary>
        internal static string Graph_GetFindRoomLists_Button {
            get {
                return ResourceManager.GetString("Graph_GetFindRoomLists_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rooms.
        /// </summary>
        internal static string Graph_GetFindRoomLists_Results_Label {
            get {
                return ResourceManager.GetString("Graph_GetFindRoomLists_Results_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;html&gt;&lt;head&gt;
        ///&lt;meta http-equiv=&apos;Content-Type&apos; content=&apos;text/html; charset=us-ascii&apos;&gt;
        ///&lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body style=&apos;font-family:calibri&apos;&gt;
        ///&lt;h2&gt;Congratulations!&lt;/h2&gt;
        ///&lt;p&gt;This is a message from the Microsoft Graph Connect Sample. You are well on your way to incorporating Microsoft Graph endpoints in your apps.&lt;/p&gt;&lt;a href=&apos;{0}&apos;&gt;See the photo you just uploaded!&lt;/a&gt;
        ///&lt;h3&gt;What&apos;s next?&lt;/h3&gt;&lt;ul&gt;
        ///&lt;li&gt;Check out &lt;a href=&apos;https://developer.microsoft.com/graph&apos;&gt;developer.microsoft.com/graph&lt;/a&gt; to start building Micro [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string Graph_SendMail_Body_Content {
            get {
                return ResourceManager.GetString("Graph_SendMail_Body_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Send email.
        /// </summary>
        internal static string Graph_SendMail_Button {
            get {
                return ResourceManager.GetString("Graph_SendMail_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Send an email.
        /// </summary>
        internal static string Graph_SendMail_Heading {
            get {
                return ResourceManager.GetString("Graph_SendMail_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a After you get the email address, optionally change the following fields and then choose the &lt;b&gt;Send email&lt;/b&gt; button:.
        /// </summary>
        internal static string Graph_SendMail_Instruction {
            get {
                return ResourceManager.GetString("Graph_SendMail_Instruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please choose the &lt;b&gt;Get email address&lt;/b&gt; button first..
        /// </summary>
        internal static string Graph_SendMail_Message_GetEmailFirst {
            get {
                return ResourceManager.GetString("Graph_SendMail_Message_GetEmailFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recipient email addresses, separated by a semicolon.
        /// </summary>
        internal static string Graph_SendMail_Recipients_Label {
            get {
                return ResourceManager.GetString("Graph_SendMail_Recipients_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Subject of email.
        /// </summary>
        internal static string Graph_SendMail_Subject_Label {
            get {
                return ResourceManager.GetString("Graph_SendMail_Subject_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sent from the.
        /// </summary>
        internal static string Graph_SendMail_Subject_Text {
            get {
                return ResourceManager.GetString("Graph_SendMail_Subject_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Success! Your mail was sent..
        /// </summary>
        internal static string Graph_SendMail_Success_Result {
            get {
                return ResourceManager.GetString("Graph_SendMail_Success_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resultado.
        /// </summary>
        internal static string Resultado {
            get {
                return ResourceManager.GetString("Resultado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sign in with Microsoft.
        /// </summary>
        internal static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sign out.
        /// </summary>
        internal static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
    }
}
